USE [master]
GO
/****** Object:  Database [DevSkill]    Script Date: 10/23/2022 10:01:08 PM ******/
CREATE DATABASE [DevSkill]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DevSkill', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DevSkill.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DevSkill_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DevSkill_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DevSkill] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DevSkill].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DevSkill] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DevSkill] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DevSkill] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DevSkill] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DevSkill] SET ARITHABORT OFF 
GO
ALTER DATABASE [DevSkill] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DevSkill] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DevSkill] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DevSkill] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DevSkill] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DevSkill] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DevSkill] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DevSkill] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DevSkill] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DevSkill] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DevSkill] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DevSkill] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DevSkill] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DevSkill] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DevSkill] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DevSkill] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DevSkill] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DevSkill] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DevSkill] SET  MULTI_USER 
GO
ALTER DATABASE [DevSkill] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DevSkill] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DevSkill] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DevSkill] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DevSkill] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DevSkill] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DevSkill] SET QUERY_STORE = OFF
GO
USE [DevSkill]
GO
/****** Object:  Table [dbo].[Address]    Script Date: 10/23/2022 10:01:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Address](
	[Street] [nchar](128) NULL,
	[City] [nchar](64) NULL,
	[Country] [nchar](64) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AdmissionTest]    Script Date: 10/23/2022 10:01:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdmissionTest](
	[StartTime] [datetime] NULL,
	[EndTime] [datetime] NULL,
	[TestFees] [decimal](18, 2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Course]    Script Date: 10/23/2022 10:01:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Course](
	[Title] [nvarchar](50) NOT NULL,
	[Teacher] [nvarchar](max) NOT NULL,
	[Topics] [nvarchar](max) NOT NULL,
	[Fees] [bigint] NOT NULL,
	[Tests] [nvarchar](max) NULL,
 CONSTRAINT [PK_Course] PRIMARY KEY CLUSTERED 
(
	[Title] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Instructor]    Script Date: 10/23/2022 10:01:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Instructor](
	[Name] [nchar](128) NOT NULL,
	[Email] [nchar](128) NOT NULL,
	[PresentAddress] [nvarchar](128) NOT NULL,
	[PermanentAddress] [nchar](128) NOT NULL,
	[PhoneNumbers] [nvarchar](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Phone]    Script Date: 10/23/2022 10:01:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Phone](
	[Number] [nchar](14) NOT NULL,
	[Extentsion] [nchar](5) NULL,
	[CountryCode] [nchar](4) NULL,
 CONSTRAINT [PK_Phone] PRIMARY KEY CLUSTERED 
(
	[Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Session]    Script Date: 10/23/2022 10:01:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Session](
	[DurationInHour] [int] NOT NULL,
	[LearningObjective] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Topic]    Script Date: 10/23/2022 10:01:08 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Topic](
	[Title] [nvarchar](50) NOT NULL,
	[Description] [nvarchar](128) NOT NULL,
	[Sessions] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Topic] PRIMARY KEY CLUSTERED 
(
	[Title] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [DevSkill] SET  READ_WRITE 
GO
